# Generated by Django 3.1.6 on 2021-02-23 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_of_order', models.CharField(choices=[('confirmed', 'Confirmed'), ('dispatched', 'Dispatched'), ('on-to-delivery', 'On delivery to you'), ('delivered', 'Delivered')], default='in_bag', max_length=120)),
                ('order_placed_date', models.DateTimeField(auto_now_add=True)),
                ('order_shipping_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
