# Generated by Django 3.1.6 on 2021-02-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210218_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_placed_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('in_bag', 'In Bag'), ('ordered', 'Ordered')], default='in_bag', max_length=120),
        ),
    ]
