# Generated by Django 3.1.6 on 2021-03-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20210223_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_placed_date',
        ),
        migrations.AddField(
            model_name='cart',
            name='order_no',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
